# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
fs_permissions = [
    { access = "read-write", path = "config/anvil_localnet"},
    { access = "read-write", path = "config/xmtp_testnet"},
    { access = "read-write", path = "config/base_sepolia"},
    { access = "read-write", path = "config/unknown"}
]

[profile.default.fuzz]
runs = 1_000

[profile.ci.fuzz]
runs = 10_000
