name: Release from tag

on:
  push:
    tags:
      - "v*"

jobs:
  artifacts:
    name: Generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0

      - name: Generate artifacts
        env:
          BUILD_TAG: ${{ github.ref_name }}
        run: dev/gen-artifacts.sh

      - uses: actions/upload-artifact@v4
        with:
          name: xmtpd-contracts
          path: ./artifacts
